#!/bin/bash

echo -e "\033[32m --TEST RECURSIVE MERGE--"

echo -e "\033[36m init"

./hsegit $1 init

echo -e '\033[36m create file1.txt with content "aaa"'

filename="$1/file1.txt"

touch $filename
echo "aaa" > $filename

echo -e "\033[36m add file1.txt"

./hsegit $1 add file1.txt

echo -e '\033[36m commit "file1.txt"'

./hsegit $1 commit file1.txt

echo -e '\033[36m create file2.txt with content "bbb"'

filename2="$1/file2.txt"

touch $filename2
echo "bbb" > $filename2

echo -e "\033[36m add file2.txt"

./hsegit $1 add file2.txt

echo -e '\033[36m commit "file2.txt"'

./hsegit $1 commit file2.txt

echo -e '\033[36m create file3.txt with content "ccc"'

filename3="$1/file3.txt"

touch $filename3
echo "ccc" > $filename3

echo -e "\033[36m add file3.txt"

./hsegit $1 add file3.txt

echo -e '\033[36m commit "file3.txt"'

./hsegit $1 commit file3.txt

echo -e '\033[36m create branch "develop"'

./hsegit $1 branch-create develop

echo -e '\033[36m create file4.txt with content "ddd"'

filename4="$1/file4.txt"

touch $filename4
echo "ddd" > $filename4

echo -e "\033[36m add file4.txt"

./hsegit $1 add file4.txt

echo -e '\033[36m commit "file4.txt"'

./hsegit $1 commit file4.txt

echo -e '\033[36m create file5.txt with content "eee"'

filename5="$1/file5.txt"

touch $filename5
echo "eee" > $filename5

echo -e "\033[36m add file5.txt"

./hsegit $1 add file5.txt

echo -e '\033[36m commit "file5.txt"'

./hsegit $1 commit file5.txt

echo -e '\033[36m checkout master'

./hsegit $1 checkout master

echo -e '\033[36m create branch "custom"'

./hsegit $1 branch-create custom

echo -e '\033[36m create file5.txt with content "fff"'

filename6="$1/file6.txt"

touch $filename6
echo "fff" > $filename6

echo -e "\033[36m add file6.txt"

./hsegit $1 add file6.txt

echo -e '\033[36m commit "file6.txt"'

./hsegit $1 commit file6.txt

echo -e '\033[36m merge develop'

./hsegit $1 merge develop

echo -e '\033[36m log'

./hsegit $1 log

rm -rf $1
