#!/bin/bash

echo -e "\033[32m --TEST CHECKOUT--"

echo -e "\033[36m init"

./hsegit $1 init

echo -e '\033[36m create file.txt with content "aaa"'

filename="$1/file.txt"

touch $filename
echo "aaa" > $filename

echo -e "\033[36m add file.txt"

./hsegit $1 add "file.txt"

echo -e '\033[36m commit "FirstCommit"'

./hsegit $1 commit "FirstCommit"

echo -e '\033[36m create file.txt with content "bbb"'

echo "bbb" > $filename

echo -e "\033[36m add file.txt"

./hsegit $1 add "file.txt"

echo -e '\033[36m commit "SecondCommit"'

./hsegit $1 commit "SecondCommit"

echo -e "\033[36m log"

./hsegit $1 log

echo -e "\033[36m checkout HEAD~1"

./hsegit $1 checkout HEAD~1

echo -e "\033[36m status"

./hsegit $1 status

echo -e "\033[36m log"

./hsegit $1 log

echo -e "\033[36m checkout master"

./hsegit $1 checkout master

echo -e "\033[36m status"

./hsegit $1 status

echo -e "\033[36m log"

./hsegit $1 log

rm -rf $1
