#!/bin/bash

echo -e "\033[32m --TEST BRANCH REMOVE--"

echo -e "\033[36m init"

./hsegit $1 init

echo -e '\033[36m create file1.txt with content "aaa"'

filename="$1/file1.txt"

touch $filename
echo "aaa" > $filename

echo -e "\033[36m add file1.txt"

./hsegit $1 add file1.txt

echo -e '\033[36m commit "file1.txt"'

./hsegit $1 commit file1.txt

echo -e '\033[36m create branch "develop"'

./hsegit $1 branch-create develop

echo -e '\033[36m create file2.txt with content "bbb"'

filename2="$1/file2.txt"

touch $filename2
echo "bbb" > $filename2

echo -e "\033[36m add file2.txt"

./hsegit $1 add file2.txt

echo -e '\033[36m commit "file2.txt"'

./hsegit $1 commit file2.txt

echo -e "\033[36m status"

./hsegit $1 status

echo -e "\033[36m checkout master"

./hsegit $1 checkout master

echo -e "\033[36m status"

./hsegit $1 status

echo -e '\033[36m remove branch "develop"'

./hsegit $1 branch-remove develop

echo -e "\033[36m show branches"

./hsegit $1 show-branches

rm -rf $1
